Add item requests
alex1056/java-shareit pull request #3
Opened 2023-04-29 06:59 UTC by alex1056

2023-05-01 09:12 UTC, ErkinKasymaliev requested changes
привет, оставил комменты.
Основное что не понравилось, вы используете nativeQuery там где можно без этого обойтись. nativeQuery обычно есть смысл использовать, когда вам нужен очень сложный запрос с множествами Джойнов, каких то подзапросов или с with table as (....
где нельзя обойтись просто средствами spring data.
Также в тестах желательно использовать метод Mockito.verify.

2023-05-01 09:12 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingByBookerIdOrderByStartDesc(Long bookerId, PageRequest pageRequest);
тут native query необязателен, можно прописать так:
`List<Booking> findAllByUser_IdOrderByStartDateDesc(Long bookerId, Pageable pageable)`

2023-05-01 09:12 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingByBookerIdOrderByStartDesc(Long bookerId, PageRequest pageRequest);
также сюда давайте передавать Pageable, так как PageRequest имплементит Pageable

2023-05-01 09:12 UTC, ErkinKasymaliev commented on src/main/java/ru/practicum/shareit/booking/repository/BookingRepository.java
> +    List<Booking> findBookingsByOwner(Long userId, PageRequest pageRequest);
смотрите коммент выше

2023-05-01 09:12 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +                .andExpect(status().isBadRequest());
еще желательно проверять вызвался ли или вызвался ли нужное кол-во раз ваш замоканный метод, в данном случае bookingService.saveBooking через метод `verify`.
`verify(bookingService, times(1)).saveBooking(any());`

2023-05-01 09:12 UTC, ErkinKasymaliev commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTests.java
> +        final NotFoundException exception3 = Assertions.assertThrows(
еще желательно проверять вызвался ли или вызвался ли нужное кол-во раз ваши замоканные методы через метод verify.

2023-05-01 19:26 UTC, alex1056 commented on src/test/java/ru/practicum/shareit/booking/BookingControllerTests.java
> +                .andExpect(status().isBadRequest());
поправил

2023-05-01 19:29 UTC, alex1056 commented on src/test/java/ru/practicum/shareit/booking/BookingServiceTests.java
> +        final NotFoundException exception3 = Assertions.assertThrows(
verify вызываю там где тип возвращаемого значения  = void, в данном методе все замоканные методы возвращают значения которые я потом проверяю. Думаю, здесь verify лишний.

2023-05-02 10:05 UTC, ErkinKasymaliev approved these changes
привет, работа принята

2023-05-02 17:48 UTC, merged